"""Build every notebook (.ipynb) and its plain-Python twin (.py) in this repo.

Why this exists
---------------
Notebooks are great in Colab but painful to diff on GitHub. This project
therefore treats HUMAN-READABLE SOURCE FILES in tools/notebook_sources/ as the
source of truth. Each source file is a plain Python module that declares its
cells as ("md" | "code", text) tuples.

Run from the repo root:

    python tools/build_notebooks.py

It regenerates, for every source module:
  * <project>/<name>.ipynb   -> a valid nbformat-4 notebook (Colab-ready)
  * <project>/<name>.py      -> a runnable script with the same code cells
                                (shell lines like `!pip install` are commented out)

Dependencies: Python 3.10+ standard library only.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = Path(__file__).resolve().parent / "notebook_sources"

NB_VERSION = 4
NB_MINOR = 5


def cell_id(index: int) -> str:
    """Stable, readable cell ids (used by Colab / Jupyter)."""
    return f"cell-{index:03d}"


def split_lines(text: str) -> list[str]:
    """Turn a cell body into the list-of-lines form nbformat expects."""
    out = []
    for line in text.split("\n"):
        if line.endswith("\n"):
            out.append(line)
        else:
            out.append(line + "\n")
    return out


def build_notebook(module) -> dict:
    """Create the notebook dict for a notebook_sources module."""
    cells = []
    for index, (kind, body) in enumerate(module.CELLS, start=1):
        if kind == "md":
            cells.append(
                {
                    "cell_type": "markdown",
                    "id": cell_id(index),
                    "metadata": {},
                    "source": split_lines(body),
                }
            )
        elif kind == "code":
            cells.append(
                {
                    "cell_type": "code",
                    "execution_count": None,
                    "id": cell_id(index),
                    "metadata": {},
                    "outputs": [],
                    "source": split_lines(body),
                }
            )
        else:
            raise ValueError(f"Unknown cell type {kind!r} in {module.NB_NAME}")
    return {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": NB_VERSION,
        "nbformat_minor": NB_MINOR,
    }


def python_twin(module) -> str:
    """Concatenate code cells into one runnable .py script.

    Notebook-only syntax is neutralised so the file is valid plain Python:
      * lines starting with '!' (shell: pip, nvidia-smi ...)  -> commented out
      * lines starting with '%' (ipython magics)              -> commented out
    """
    header = (
        "# This file is a plain-Python twin of "
        f"{module.NB_NAME} (generated by tools/build_notebooks.py).\n"
        "# Notebook-only lines (pip installs, magics, shell commands) are kept "
        "as comments.\n"
        "# Run locally after installing the dependencies printed in the README.\n"
        "\n"
    )
    chunks = [header]
    code_idx = 0
    for kind, body in module.CELLS:
        if kind != "code":
            continue
        code_idx += 1
        chunks.append(f"\n# {'=' * 70}\n# [ cell {code_idx} ]\n# {'=' * 70}\n\n")
        kept = []
        for raw_line in body.split("\n"):
            stripped = raw_line.strip()
            if stripped.startswith("!") or stripped.startswith("%"):
                kept.append("# " + raw_line)
            else:
                kept.append(raw_line)
        chunks.append("\n".join(kept))
    return "".join(chunks)


def write_module(module_path: Path) -> None:
    spec = importlib.util.spec_from_file_location(
        "notebook_source_" + module_path.stem, module_path
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]

    out_dir = ROOT / module.OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    nb_path = out_dir / module.NB_NAME
    nb_path.write_text(
        json.dumps(build_notebook(module), indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    py_path = out_dir / module.PY_NAME
    py_path.write_text(python_twin(module), encoding="utf-8")
    print(f"[ok] {nb_path.relative_to(ROOT)}")
    print(f"[ok] {py_path.relative_to(ROOT)}")


def main() -> int:
    modules = sorted(SOURCES_DIR.glob("*.py"))
    if not modules:
        print("No notebook source modules found in", SOURCES_DIR)
        return 1
    for module_path in modules:
        write_module(module_path)
    print(f"\nDone. Built {len(modules)} notebook(s) + python twin(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
