# This file is a plain-Python twin of baseline_mnist_cnn.ipynb (generated by tools/build_notebooks.py).
# Notebook-only lines (pip installs, magics, shell commands) are kept as comments.
# Run locally after installing the dependencies printed in the README.


# ======================================================================
# [ cell 1 ]
# ======================================================================

# ============================================================
# 1) SETUP — installs, imports, device
# ============================================================
# !pip install -q torch torchvision matplotlib

import time
import os
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", DEVICE)
print("torch:", torch.__version__)

# ======================================================================
# [ cell 2 ]
# ======================================================================

# ============================================================
# 2) LOAD MNIST  (subset: 12k train / 2k test)
# ============================================================
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

transform = transforms.ToTensor()   # pixels -> tensor in [0, 1]

train_full = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_full = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_set = Subset(train_full, list(range(12000)))
test_set = Subset(test_full, list(range(2000)))

BATCH = 64
train_loader = DataLoader(train_set, batch_size=BATCH, shuffle=True)
test_loader = DataLoader(test_set, batch_size=BATCH, shuffle=False)

print(f"train samples: {len(train_set)}   test samples: {len(test_set)}")

# --- look at a few digits -----------------------------------------
images, labels = next(iter(train_loader))
fig, axes = plt.subplots(1, 6, figsize=(8, 2))
for i in range(6):
    axes[i].imshow(images[i].squeeze(), cmap="gray")
    axes[i].set_title(f"label={labels[i].item()}")
    axes[i].axis("off")
plt.tight_layout()
plt.show()

# ======================================================================
# [ cell 3 ]
# ======================================================================

# ============================================================
# 3) DEFINE THE TINY CNN + count parameters
# ============================================================
class TinyCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 128), nn.ReLU(),
            nn.Linear(128, 10),
        )

    def forward(self, x):
        return self.classifier(self.features(x))


model = TinyCNN().to(DEVICE)
n_params = sum(p.numel() for p in model.parameters())
print(f"TinyCNN parameters: {n_params:,}")

# ======================================================================
# [ cell 4 ]
# ======================================================================

# ============================================================
# 4) TRAIN + EVALUATE + SAVE
# ============================================================
def train_one_epoch(model, loader, opt, loss_fn):
    model.train()
    total = correct = 0
    for x, y in loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        opt.zero_grad()
        loss = loss_fn(model(x), y)
        loss.backward()
        opt.step()
        total += y.numel()
        correct += (model(x).argmax(1) == y).sum().item()
    return correct / total


def evaluate(model, loader):
    model.eval()
    total = correct = 0
    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            correct += (model(x).argmax(1) == y).sum().item()
            total += y.numel()
    return correct / total


opt = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()

print("Training the baseline ...")
for epoch in range(1, 4):
    t0 = time.time()
    acc = train_one_epoch(model, train_loader, opt, loss_fn)
    print(f"epoch {epoch}: train acc = {acc:.4f}  ({time.time()-t0:.0f}s)")

test_acc = evaluate(model, test_loader)
print(f"\nCLEAN test accuracy = {test_acc:.4f}  ({test_acc*100:.1f}%)")

os.makedirs("./models", exist_ok=True)
torch.save(model.state_dict(), "./models/baseline_mnist.pt")
print("saved -> ./models/baseline_mnist.pt")

# ======================================================================
# [ cell 5 ]
# ======================================================================

# ============================================================
# 5) LOOK AT CONFIDENCE (softmax) FOR A FEW TEST IMAGES
# ============================================================
import torch.nn.functional as F

model.eval()
images, labels = next(iter(test_loader))
images, labels = images.to(DEVICE), labels.to(DEVICE)

with torch.no_grad():
    probs = F.softmax(model(images[:5]), dim=1)

for i in range(5):
    p = probs[i]
    pred = p.argmax().item()
    conf = p.max().item()
    print(f"true={labels[i].item()}  pred={pred}  confidence={conf:.3f}  "
          f"({'correct' if pred == labels[i].item() else 'WRONG'})")
